- name: Lab AWX - 3 tarefas
  hosts: all
  become: true
  tasks:

    - name: 1 - Testar conectividade
      ping:

    - name: 2 - Criar arquivo
      file:
        path: /tmp/awx-lab.txt
        state: touch

    - name: 3 - Escrever conteúdo no arquivo
      copy:
        dest: /tmp/awx-lab.txt
        content: "Arquivo criado pelo AWX 🚀"
