---
# teste execucao 3
- name: Padronizacao basica de servidor Linux
  hosts: minha_vm
  become: true

  vars:
    evidence_file: /etc/awx-managed.conf

  tasks:
    - name: 1 - Garantir pacote chrony instalado
      ansible.builtin.package:
        name: chrony
        state: present

    - name: 2 - Garantir servico chronyd ativo e habilitado
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true

    - name: 3 - Criar arquivo de evidência
      ansible.builtin.copy:
        dest: "{{ evidence_file }}"
        content: |
          managed_by=awx
          pipeline=github_actions_v2
          owner=rafael
        owner: root
        group: root
        mode: "0644"
